### ISSUE TITLE
Update to CE 1.10.1

### ISSUE THREAD

**Issue by tmewett** [sethhoward/iBrogueCE#1]
Seth has kindly agreed to resume publishing on the App Store, but will not be working on the code. So, we need someone with an iPad to update the app to the latest CE, test it, then make a PR for the changes.

(From the looks of things this is software without an explicit maintainer and a [small backlog of issues/ideas](https://github.com/sethhoward/Brogue-iPad/issues), so might be a nice small project to pick up for someone interested in iOS dev.)

**Comment by sluedecke** [comment]
Looks good in my emulator so far, I can start the 1.3.5 from this repository and will look into patching it up to 1.10.1.

iBrogueCE does not have a license set, @sethhoward: can I kindly ask you to choose one?

**Comment by sluedecke** [comment]
So I started the update and after reviewing all the differences it still does not compile due to some (no longer legal?) typecasts.  Will work another day on this.

**Comment by tmewett** [comment]
I don't believe they have a choice in licensing; original Brogue is AGPLv3 which is copyleft so applies to derivatives

**Comment by sluedecke** [comment]
I am a bit out of luck ... the compiler complains about type conversions between enums and int on many MANY places, e.g.

Time.mm:42
```
messageWithColor(buf2, messageColorFromVictim(monst), 0);
```
tells me:

> Rogue.h:2922:10: Candidate function not viable: no known conversion from 'int' to 'enum messageFlags' for 3rd argument

This affects almost all usages of message and similar functions.  I did not find a compiler switch to have this conversion ignored and I am reluctant to extend messageFlags with a `NO_FLAGS = 0` entry and change all these lines.  Though this will work, it will make merging Broge from upstream very hard.

Any ideas how to handle this efficiently?

**Comment by tmewett** [comment]
This argument to the message functions shouldn't really be an enum type. The enum is for the individual bitflags, but a union of the flags will take values outside the enum, so should be an unsigned integer type. I will push a commit to CE that you can cherry pick onto this repo

**Comment by Rashern** [comment]
You guys are my heroes getting this up and running again.I've always wanted
to play it on my Ipad. Tried compiling it a while back but got all sorts of
errors and had no idea what I was doing to fix them. (As I could see, you
could still upload it in test mode to an ipad somehow)

**Comment by sluedecke** [comment]
@tmewett: Thanks for the patch, that makes the compiler a bit happier ... but a bit only, there are other, similar things it complains about in Time.mm (line numbers might be approximate due to some iPad specific additions, also Time.mm == Time.c from upstream):

Time.mm
- e.g. Time.mm:234:22: Assigning to 'enum dungeonLayers' from incompatible type 'int'
original statements
`for (layer = 0; layer < NUMBER_TERRAIN_LAYERS; layer++)`
working replacement as of https://stackoverflow.com/a/41718764/3079262
`for (layer = DUNGEON; layer < NUMBER_TERRAIN_LAYERS; layer = dungeonLayers(layer + 1))`

also affected
- `for (layer=0; layer < NUMBER_TERRAIN_LAYERS; layer++)`
- `for (layer = 0; layer < NUMBER_TERRAIN_LAYERS && !(tileCatalog[pmap[*x][*y].layers[layer]].flags & T_CAUSES_EXPLOSIVE_DAMAGE); layer++);`
- `for (dir = 0, explosiveNeighborCount = 0; dir < DIRECTION_COUNT; dir++)`
- `for (dir = 0; dir < DIRECTION_COUNT; dir++)`
- `for (dir=0; dir< DIRECTION_COUNT; dir++)`
- `for (dir = 0; dir < 4; dir++)` -> `(dir = UP; dir < UPLEFT; directions(dir + 1))`

I patched those in https://github.com/sluedecke/iBrogueCE/commit/8a6d2eb0383a89934da1ec8e41ed5e8eb9b9e233 and made another adaption in https://github.com/sluedecke/iBrogueCE/commit/69026cc5a447440e08860fe84237cae63d3d57f1.

So far so good, the code in https://github.com/sluedecke/iBrogueCE/tree/brogue-1.10.1 finally compiles but linking fails.  I will look into that as well.

**Comment by sluedecke** [comment]
P.S.: the adaptions in Time.c/mm could probably be done by making `dir` and `layer` unsigned longs but somehow I was reluctant to make these - admittedly much simpler - fixes: now it feels a bit more type safe.  @tmewett which way would you have preferred?

**Comment by sluedecke** [comment]
This is the linker error I have to solve next:

```
Ld /Users/makkie/Library/Developer/Xcode/DerivedData/iBrogueCE_iPad-bjhrdijbduelhifmqzrwsjptxvwu/Build/Intermediates.noindex/iBrogueCE_iPad.build/Release-iphoneos/iBrogueCE_iPad.build/Objects-normal/armv7/Binary/BrogueCE normal armv7 (in target 'iBrogueCE_iPad' from project 'iBrogueCE_iPad')
    cd /Users/makkie/Desktop/Development/BROGUE/iBrogueCE
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -target armv7-apple-ios10.0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.5.sdk -L/Users/makkie/Desktop/Development/BROGUE/iBrogueCE/build/Release -F/Users/makkie/Desktop/Development/BROGUE/iBrogueCE/build/Release -filelist /Users/makkie/Library/Developer/Xcode/DerivedData/iBrogueCE_iPad-bjhrdijbduelhifmqzrwsjptxvwu/Build/Intermediates.noindex/iBrogueCE_iPad.build/Release-iphoneos/iBrogueCE_iPad.build/Objects-normal/armv7/BrogueCE.LinkFileList -Xlinker -rpath -Xlinker /usr/lib/swift -Xlinker -rpath -Xlinker @executable_path/Frameworks -dead_strip -Xlinker -object_path_lto -Xlinker /Users/makkie/Library/Developer/Xcode/DerivedData/iBrogueCE_iPad-bjhrdijbduelhifmqzrwsjptxvwu/Build/Intermediates.noindex/iBrogueCE_iPad.build/Release-iphoneos/iBrogueCE_iPad.build/Objects-normal/armv7/BrogueCE_lto.o -fembed-bitcode-marker -fobjc-arc -fobjc-link-runtime -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphoneos -L/usr/lib/swift -Xlinker -add_ast_path -Xlinker /Users/makkie/Library/Developer/Xcode/DerivedData/iBrogueCE_iPad-bjhrdijbduelhifmqzrwsjptxvwu/Build/Intermediates.noindex/iBrogueCE_iPad.build/Release-iphoneos/iBrogueCE_iPad.build/Objects-normal/armv7/BrogueCE.swiftmodule -framework QuartzCore -framework UIKit -framework Foundation -framework CoreGraphics -Xlinker -no_adhoc_codesign -Xlinker -dependency_info -Xlinker /Users/makkie/Library/Developer/Xcode/DerivedData/iBrogueCE_iPad-bjhrdijbduelhifmqzrwsjptxvwu/Build/Intermediates.noindex/iBrogueCE_iPad.build/Release-iphoneos/iBrogueCE_iPad.build/Objects-normal/armv7/BrogueCE_dependency_info.dat -o /Users/makkie/Library/Developer/Xcode/DerivedData/iBrogueCE_iPad-bjhrdijbduelhifmqzrwsjptxvwu/Build/Intermediates.noindex/iBrogueCE_iPad.build/Release-iphoneos/iBrogueCE_iPad.build/Objects-normal/armv7/Binary/BrogueCE
Undefined symbols for architecture armv7:
  "_notifyEvent", referenced from:
      _executePlaybackInput in Recordings.o
      _gameOver in RogueMain.o
      _victory in RogueMain.o
  "_initializeLaunchArguments", referenced from:
      _mainBrogueJunction in MainMenu.o
  "_hasGraphics", referenced from:
      _actionMenu in IO.o
      _executeKeystroke in IO.o
      _executePlaybackInput in Recordings.o
  "_serverMode", referenced from:
      _actionMenu in IO.o
      _executeKeystroke in IO.o
      _mainBrogueJunction in MainMenu.o
      _getDefaultFilePath in Recordings.o
      _gameOver in RogueMain.o
      _victory in RogueMain.o
  "_isApplicationActive", referenced from:
      _titleMenu in MainMenu.o
  "_graphicsMode", referenced from:
      _actionMenu in IO.o
      _executeKeystroke in IO.o
      _executePlaybackInput in Recordings.o
  "_takeScreenshot", referenced from:
      _executeKeystroke in IO.o
  "_tryParseUint64", referenced from:
      _mainBrogueJunction in MainMenu.o
  "_setGraphicsMode", referenced from:
      _executeKeystroke in IO.o
      _executePlaybackInput in Recordings.o
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by tmewett** [comment]
Hmm, that stackoverflow link about iterating enums is for C++. And looking at the filename Time.mm, isn't that the suffix for Objective-C++? Was the file always called that? Brogue is written in C and won't compile as C++. Does Time.m work, or maybe you can change the language in the environment somehow?

**Comment by SeymourJ** [comment]
Has progress on this branch stopped?

**Comment by apollovy** [comment]
Ok, I've fixed the linker issue and a couple of others in https://github.com/apollovy/iBrogueCE/tree/brogue-1.10.1, the game launches, but there is no map / game field, as shown on screenshot.
I'm not 100% sure for [these](https://github.com/apollovy/iBrogueCE/blob/207a6eb16722873d79f93b34944ac73ec780afae/iBrogueCE_iPad/BrogueCode/platformdependent.c#L564-L567) lines, but I believe the last is the reason: there's no console initialized:
```
boolean hasGraphics = true;
boolean serverMode = false;
enum graphicsModes graphicsMode = TILES_GRAPHICS;
struct brogueConsole currentConsole;
```
And I just don't get now how it used to work, because it seems like no dependencies neither for SDL, nor for curses were present in the previous versions
![Simulator Screen Shot - iPad Pro (12 9-inch) (4th generation) - 2021-10-18 at 22 12 11](https://user-images.githubusercontent.com/1671727/137793934-029d4d71-944f-41ff-b184-98bd623c0b99.png)

**Comment by tmewett** [comment]
iPad is drawn via ASCII by a custom platform backend in PlatformCode/RogueDriver.mm. Looking at the current iBrogueCE, it looks like PlatformCode hasn't been updated since the backend API changes introduced by tiles in tmewett/BrogueCE#81, so probably needs changes. (The summary is that Unicode no longer comes in to plotChar, you get displayGlyphs which need to be mapped to something.) You'll want to refer to the platform files in the main CE source (maybe the curses one is most appropriate). It's possible all it needs is a call to glyphToUnicode (platformdependent.c) somewhere.

**Comment by SeymourJ** [comment]
I downloaded and built the source of apollovy's branch of CE 1.10.1 for iOS today.  It does run, but I am seeing some 
weird screen character issues in both the iPad9 simulator built into Xcode and on my physical iPad 5th Gen.

Rings appear as solid circles in this build, while in all previous builds they appear as hollowed circles.

Also, some landscape characters in the dungeon are initially drawn as this weird colored V character,  When I move my @ over them and then away, they correctly draw as " (grass) or whatever, but the initial view of the level is not correct.

Here is a cropped screen shot from my iPad 5th Gen:

![IMG_0557](https://user-images.githubusercontent.com/91446868/138536167-8ce700ce-8712-4ee6-ba00-cad0d5c46660.jpeg)

**Comment by SeymourJ** [comment]
Just trying to be helpful.  I'm no expert at Xcode or development in general.  If my input isn't helpful, or this isn't the proper forum for it, please let me know.
